### ISSUE TITLE
Can't compile on Rocky Linux 9.0

### ISSUE THREAD

**Issue by TanerKaragol** [thkukuk/ypserv#15]
make command gives error:

yp.h:10:10 fatal error: rpcsvc/yp_prot.h: No such file or directory

**Comment by thkukuk** [comment]
You need to install the package which provides rpcsvc/yp_prot.h, don't know which this is on Rocky Linux 9.0.
